functions/invoke-d365scdpbundleinstall.ps1
functions/invoke-d365sdpinstall.ps1

- Unblock on downloaded file
- Check for TfsUri
- Fix order of operations when doing a "RunAll" command for SDPInstall

Fixes on SDPInstall and SCDPBundleInstall

---

functions/invoke-d365scdpbundleinstall.ps1

Half a second was not precice enough. 0.1 second is more accurate.

Increase update fidelity

---

d365fo.tools/functions/disable-d365maintenancemode.ps1
d365fo.tools/functions/enable-d365maintenancemode.ps1

- Start and Stop Environment when (de)activating maintenance mode while running in admin mode
- only start AOS after enabling maintenance mode; batch won't start anyway and also DMF and MMR should not run in maintenance mode

Start and Stop Environment when (de)activating maintenance mode

---

d365fo.tools/internal/functions/import-aaduserIntod365fo.ps1

I noticed there were a couple of typos in the import-aaduserintod365fo internal function where messages were output to the console. I have fixed these typos. This is to fix issue #174

Fixed a couple of typos in the import-aaduserintod365fo internal function

---

d365fo.tools/d365fo.tools.psd1
d365fo.tools/functions/set-d365flightservicecatalogid.ps1

Inspired by your test-cmdlet I've created the set-cmdlet, which now should make it a complete story:
```
If (-not (Test-D365FlightServiceCatalogId))
{
Set-D365FlightServiceCatalogId
}
Enable-D365Flight MagicFlight
```

Feature: implement set-d365flightservicecatalogid

---

d365fo.tools/d365fo.tools.psd1
d365fo.tools/functions/add-d365windowsdefenderrule.ps1

With the installation of Visual Studio 2019 I also found out about windows defender rules that can improve the performance while working on a DevBox.
I added a function to add those rules to the windows defender - if it's enabled.
About the tags in the synopsis: I was unsure what to write there, please check it and add accordingly.
Hopefully this function is useful for the d365fo.tools module.

Add function for windows defender rules (performance)

---

d365fo.tools/functions/invoke-d365modulecompile.ps1

Add the -xref option to Invoke-D365ModuleCompile to enable the creation of cross references during compilation

Invoke-D365ModuleCompile: Add -xref option

---

d365fo.tools/functions/invoke-d365lcsenvironmentstart.ps1
d365fo.tools/functions/invoke-d365lcsenvironmentstop.ps1
d365fo.tools/internal/functions/start-lcsenvironmentstartstop.ps1

There is an update going out to the LCS backend API this week to disallow the Start and Stop API endpoints from working with Microsoft Managed environments. This PR is to update the documentation notes for the D365FO.tools methods that use the backend APIs.
Microsoft Managed environments are required to be online for Microsoft infrastructure and application updates. Since the cost for these environments running are on Microsoft, there is no cost savings for customers by stopping these environments through the API. 
If we have enough demand, we can enable Sandbox Microsoft Managed support. For now, the restriction for all Microsoft Managed environments is now in place.
In addition, updating the author property to correctly include Mötz for writing the base structure for this method.

Update Start Stop environment API notes

---

d365fo.tools/internal/functions/get-syncelements.ps1

Changing the metadata provider from disk to runtime enables partial database synchronization for modules that are only available in binary form.
d365collaborative/d365fo.tools#516

Get-SyncElements: change DiskProvider to RuntimeProvider

---

d365fo.tools/functions/invoke-d365dbsyncpartial.ps1
d365fo.tools/internal/functions/get-syncelements.ps1
d365fo.tools/tests/functions/Invoke-D365DBSyncPartial.Tests.ps1

By making the SyncList parameter optional, the partial database sync can also be executed for modules that only have extensions of synchronizable objects (e.g. only table extensions).
#515

Invoke-D365DbSyncPartial: make SyncList parameter optional

---

.github/workflows/update-wiki.yml
wiki/How-To-Import-Bacpac-Into-Tier1.md

Turns out that the [Publish to GitHub Wiki](https://github.com/SwiftDocOrg/github-wiki-publish-action) GitHub action only publishes .md files to the wiki repository. I changed the action to a work in progress branch to include all files that are in the wiki folder.
The commits are a bit messy. I first started with a clean up of some broken links. When I published this, I noticed that in my wiki, the images were missing. I first tried another GitHub action, which included the images but had other issues. Then I modified the original GitHub action to have it include all files, only to realize that the repo of the GitHub action already has a work in progress branch that solves that issue.

fix some wiki links and improve wiki publishing

---

d365fo.tools/d365fo.tools.psd1
d365fo.tools/functions/get-d365webservertype.ps1
d365fo.tools/functions/set-d365webservertype.ps1
d365fo.tools/tests/functions/Get-D365WebServerType.Tests.ps1
d365fo.tools/tests/functions/Set-D365WebServerType.Tests.ps1
docs/Get-D365WebServerType.md
docs/Set-D365WebServerType.md

Added `Get-D365WebServerType` and  `Set-D365WebServerType` cmdlets which allow you to quickly change the web server to either IIS or IIS Express.
Both cmdlets are nearly identical to the existing `Get-D365DefaultModelForNewProjects` / `Set-D365DefaultModelForNewProjects` cmdlets which also replace the value of a specific XML node. Only thing I'm not quite sure of is the location of the `DynamicsDevConfig.xml` file. It will currently look for this file in `K:\AosService\PackagesLocalDirectory\bin\`, which should be the default service drive for most dev boxes...
- 💪 Fixes d365collaborative/d365fo.tools#571.
- ✔ added documentation
- ✔ added tests

✨ Added cmdlets  to manage web server type

---

d365fo.tools/functions/import-d365aaduser.ps1

Adding functionality to be able to use the UserPrincipalName in de AAD as the IDValue for Import-D365AadUser.
Some companies have multiple domains resistered to their AAD and the emailaddress of user is not equal to the actual loginname that is used in the AAD, therefore when using the 'Login' ad IdValue in Import-D365AadUser will cause the user to be unable to login the D365 environment.

Change Import-D365AadUser added UserPrincipalName to support UserPrincipalName #611

---

d365fo.tools/functions/add-d365windowsdefenderrules.ps1

Also adding testhost.exe as windows defender exclusion to speed up unit test executions.

feat: adding testhost.exe as windows defender exclusion

---

d365fo.tools/functions/import-d365externaluser.ps1

SSRS reports not working anymore for external users starting from version 10.0.21 (PU 45)
The IdentityProvider assigned by `Import-AadUserIntoD365FO` is currently ` https://sts.windows.net/[AADTenantName]` instead of ` https://sts.windows.net/[AADTenantID]`. This causes the SSRS reports to throw "Forbidden" at external users. 
From Microsoft Support:
`The correct value for the IdentityProvider column needs to be https://sts.windows.net/ or https://sts.windows.net/[AADTenantId] in case that the user email has a different domain than admin domain (as in our case).`

Fixed IdentityProvider param for 'Import-AadUserIntoD365FO' function

---

.github/workflows/update-wiki.yml

Use a modified SwiftDocOrg/github-wiki-publish-action to fix the "fatal: unsafe repository" issue when running the update-wiki.yml action.
Due to a security change in Git made in April, the SwiftDocOrg/github-wiki-publish-action used in the update-wiki.yml fails with a "fatal: unsafe repository" error message. See https://github.com/actions/checkout/issues/760 for more information.
I modified SwiftDocOrg/github-wiki-publish-action in my fork to adress this issue. Since SwiftDocOrg/github-wiki-publish-action has also been archived by the owner, we should continue to use my fork for the time being. At some time, I want to look into replacing it by another GitHub action that provides the same capabilities.

fix fatal unsafe repository issue for update-wiki.yml

---

d365fo.tools/functions/rename-d365computername.ps1

When used in a VS2019 VHD the Rename-D365ComputerName CmdLet issues an error message "Invalid namespace" while setting the SSRS database, because the Reporting Services instance is named SSRS instead of the expected default name RSServer.

Update Rename-D365ComputerName.ps1: Set SSRS instance name for VS2019 VHD

---

d365fo.tools/internal/functions/invoke-process.ps1

When reading the standard output and error streams, synchronously - we could end up with a race condition and deadlocks based on several things

Fix: Race condition

---

d365fo.tools/functions/get-d365module.ps1

I believe that using `$Script:Script:PackageDirectory` was wrong. If another value was provided in `$PackageDirectory` parameter, we should use it, instead of ignoring it and using the default value anyway.

Metadata provider to use path from parameter

---

d365fo.tools/functions/get-d365module.ps1
d365fo.tools/tests/functions/Get-D365Module.Tests.ps1
docs/Get-D365Module.md
wiki/How-To-Compile-Model.md
wiki/How-To-List-Models.md

An ability of `Get-D365Module` to return modules in the order in which they should be compiled.
The commit includes changes to documentation and tests.

InDependencyOrder param added to Get-D365Module

---

d365fo.tools/functions/get-d365model.ps1

A minor change, equivalent to what we did in `Get-D365Module`.
`$Script:PackageDirectory` is used as a default value of `$PackageDirectory` and then we should always refer to `$PackageDirectory`, not `$Script:PackageDirectory`.

Use PackageDirectory from parameter

---

d365fo.tools/functions/get-d365module.ps1

The previous logic verified that the bin folder existsed, but if it was there and the file didn't, Get-FileVersion failed.
#679

Check DLL existence before getting its version.

---

.github/workflows/update-wiki.yml
README.md

See #701 
Modifies the github action that synchronizes the repo's wiki folder with the wiki repo to also include the docs folder.

:memo: add docs folder to wiki

---

.github/workflows/build.yml

Adds a Github build action that runs the unit tests scripts in the build folder.
This is an attempt to do the same with a Github action as the current build pipeline in Azure DevOps does: https://dev.azure.com/Splaxi/d365fo.tools/_build?definitionId=20&_a=summary
@Splaxi Not sure if you want to merge this and replace your Azure DevOps pipeline (or have both). I had some fun today getting this to work and learned a bit about caching 😃

add Github build action

---

d365fo.tools/functions/invoke-d365installsqlpackage.ps1

The default SqlPackage version is updated to 19.1, which is the last version based on .NET Core.
See https://github.com/d365collaborative/d365fo.tools/issues/708 for further discussion on this change.

:package: update default SqlPackage version

---

d365fo.tools/functions/import-d365bacpac.ps1
d365fo.tools/tests/functions/Import-D365Bacpac.Tests.ps1
docs/Import-D365Bacpac.md

Enables power users of the cmdlet to provide a list of properties to be used by SQLPackage to customize the bacpac import.
#648

:sparkles: add SQLPackage properties parameter

---

d365fo.tools/internal/sql/rename-computer.sql

Previously, @OldComputerName was used to remove the existing SQL Server. This was based on the assumption that the SQL Server's name is identical to the computer name of the VHD. However, since the 10.0.29 VHD, this is no longer true.
fixes #704

:bug: fix computer renaming

---

d365fo.tools/functions/import-d365bacpac.ps1

:bug: remove duplicate -TrustedConnection parameters

---

d365fo.tools/functions/get-d365lcsenvironmentrsatcertificate.ps1
d365fo.tools/functions/import-d365rsatselfservicecertificates.ps1
d365fo.tools/tests/functions/Import-D365RsatSelfServiceCertificates.Tests.ps1
docs/Get-D365LcsEnvironmentRsatCertificate.md
docs/Import-D365RsatSelfServiceCertificates.md

- fixes a copy&paste issue in the documentation of the new Get-D365LcsEnvironmentRsatCertificate
- adds experimental pipeline support so the result of Get-D365LcsEnvironmentRsatCertificate can be piped to Import-D365RsatSelfServiceCertificates

Fix documentation and enable pipeline from download to import

---

d365fo.tools/functions/import-d365rsatselfservicecertificates.ps1
d365fo.tools/tests/functions/Import-D365RsatSelfServiceCertificates.Tests.ps1
docs/Import-D365RsatSelfServiceCertificates.md

The changes from #803 to enable pipelining the output from Get-D365LcsEnvironmentRsatCertificate to Import-D365RsatSelfServiceCertificates did not work. An error ocurred that the $Password and $Path parameters are empty. This was caused because some logic that operates on the parameters was placed in the begin block of the Import-D365RsatSelfServiceCertificates cmdlet. Piped input is only available in the process block.

Fix import rsat certificate pipeline

---

d365fo.tools/d365fo.tools.psd1
d365fo.tools/functions/backup-d365devconfig.ps1
d365fo.tools/functions/backup-d365runbook.ps1
d365fo.tools/functions/backup-d365webconfig.ps1
d365fo.tools/functions/backup-d365wifconfig.ps1
d365fo.tools/functions/new-d365entraintegration.ps1
d365fo.tools/functions/rename-d365instance.ps1
d365fo.tools/functions/test-d365entraintegration.ps1
d365fo.tools/internal/functions/backup-file.ps1
d365fo.tools/internal/scripts/variables.ps1
d365fo.tools/tests/functions/Backup-D365WifConfig.Tests.ps1
d365fo.tools/tests/functions/New-D365EntraIntegration.Tests.ps1
docs/Backup-D365WifConfig.md
docs/New-D365EntraIntegration.md

closes #796 
As described in #796 , this adds an optional switch `-AddAppRegistrationToWifConfig` to the `New-D365EntraIntegration` cmdlet.
As a prerequisite, a new cmdlet `Backup-D365WifConfig` was created to enable creating a backup of the wif.config file.
As part of that, the logic of multiple file backup cmdlets was centralized in the internal `Backup-File` function.
A test for the wif.config was also added to the `Test-D365EntraIntegration` cmdlet, though a missing value will not be reported as an error, just a suggestion.

Improve entra integration

---

wiki/Configuration.md
wiki/_Sidebar.md

This pull request adds documentation explaining how default values are determined in the d365fo.tools module. It provides an example and explains the use of script scope and configuration values.

Add documentation for default values in d365fo.tools module

---

d365fo.tools/internal/functions/invoke-sqlpackage.ps1

The installation documentation for SqlPackage says: Installing SqlPackage as a global tool makes it available on your path as sqlpackage and is the recommended method to install SqlPackage for Windows, macOS, and Linux.
In line with Microsoft's expectations, also search %PATH% if sqlpackage is not found in the d365fo.tools default path ($Script:SqlPackagePath). If it is found in the %PATH% then update the default path with the actual path to sqlpackage.exe.
Author: Colin Daley
Date: 2024-03-24

Also search %PATH% for sqlpackage.exe

---

d365fo.tools/functions/get-d365module.ps1

If a module that is read by the disk metadata provider references a binary-only module, the "ListModulesInDependencyOrder()" method causes an exception error that is catched by the Get-D365Module function in line 172. As a result, the order of the modules cannot be determined taking the dependencies into account and "ListModules" is used instead. The problem can be easily avoided by adding the model manifest of the runtime metadata provider to the "CreateDiskProvider" method in line 165.
This ensures that the disk provider has all the information it needs to determine the sequence for all modules based on the dependencies.

Disk provider binary-only module reference fix

---

d365fo.tools/bin/d365fo.tools-index.json
d365fo.tools/functions/invoke-d365installsqlpackage.ps1
d365fo.tools/internal/functions/invoke-process.ps1
d365fo.tools/internal/functions/invoke-sqlpackage.ps1
d365fo.tools/tests/functions/Invoke-D365InstallSqlPackage.Tests.ps1
docs/Invoke-D365InstallSqlPackage.md
wiki/Call-Internal-Functions.md

This updates the default version of SqlPackage that d365fo.tools installs to 162.2.111.2 (the first .NET 8 version).
In addition, it replaces the `-SkipExtractFromPage` parameter and the corresponding web scraping logic with the `-Latest` parameter and the evergreen link https://aka.ms/sqlpackage-windows
Note that unlike the behavior from when the web scraping logic was still working, the latest version of SqlPackage is NOT installed by default. Instead, the fixed version 162.2.111.2 is installed (which may be updated to later versions in the future). Reasons for this change in behavior are discussed in #747.
The changes also include
- giving `Invoke-Process` a return value with the standard and error output
- `Invoke-D365InstallSqlPackage` and `Invoke-SqlPackage` make use of that output …

Update Invoke-D365InstallSqlPackage to install latest version of SQLPackage

---

d365fo.tools/internal/functions/start-lcsuploadv2.ps1

Quick fix for missing $jsonDescription and correcting the token parameter.

Bugfix for Issue 839: File Description not correctly set in LCS Asset upload

---

d365fo.tools/bin/d365fo.tools-index.json
d365fo.tools/d365fo.tools.psd1
d365fo.tools/functions/get-d365sdpdetails.ps1
d365fo.tools/functions/invoke-d365sdpinstall.ps1
d365fo.tools/functions/invoke-d365sdpinstallude.ps1
d365fo.tools/tests/functions/Invoke-D365SDPInstall.Tests.ps1
d365fo.tools/tests/functions/Invoke-D365SDPInstallUDE.Tests.ps1
docs/Invoke-D365SDPInstall.md
docs/Invoke-D365SDPInstallUDE.md

Related to #855 
Since I saw a couple of discussions on how to install ISV solutions on a UDE environment, I created `Invoke-D365SDPInstallUDE` to handle the extracting of the package and inner module archives into the right place.
Once we have a representation of the UDE configurations in d365fo.tools, the `-MetaDataDir` parameter can also be defaulted to the metadata directory of the active configuration.
Along the way, I encountered some issues with `Get-D365SDPDetails` which are fixed by this pr as well.

:sparkles: add new cmdlet to install a package on a unified development environment

---

.github/workflows/build.yml
.github/workflows/update-generated-text.yml
.github/workflows/update-wiki.yml
build/buildtools.ps1
build/vsts-prerequisites.ps1

This pull request includes several infrastructure changes:
1. To make analysis of issues like https://github.com/PowershellFrameworkCollective/psframework/issues/645 easier in the future, the information about what modules and versions are used in an action run are now logged - https://github.com/d365collaborative/d365fo.tools/pull/865/commits/ba66eeb86540e59762339955c35b5a293a655682
1. The first change in update-generated-text.yml fixes an issue with the cache key for the PowerShell modules - https://github.com/d365collaborative/d365fo.tools/pull/865/commits/a5bbd6f75460a37990c939f68039ee0788ca45cb
1. The second change in update-generated-text.yml is to create a unique branch name for each pull request. This ensures that fixes for one pull request are not overwritten by fixes for another …

Improve actions

---

d365fo.tools/bin/d365fo.tools-index.json
d365fo.tools/d365fo.tools.psd1
d365fo.tools/functions/publish-d365webresources.ps1
d365fo.tools/internal/functions/publish-d365foresources.ps1
d365fo.tools/tests/functions/Publish-D365WebResources.Tests.ps1
docs/Publish-D365WebResources.md

I was recently bitten by the fact that web resources contained in resource objects in the AOT are not automatically deployed to the web resource folders when a module is retrieved from a version control repository.
This is a known issue, see https://www.yammer.com/dynamicsaxfeedbackprograms/#/Threads/show?threadId=555026298970112
While there is a workaround with scripts provided in deployable packages, it is cumbersome to use. Hence the new `Publish-D365WebResources` function to make adding the missing resource files simpler.

:sparkles: Adds new function Publish-D365WebResources to simplify this process

---

d365fo.tools/bin/d365fo.tools-index.json
d365fo.tools/functions/get-d365azurestoragefile.ps1
docs/Get-D365AzureStorageFile.md

Fixes a bug with the file sorting in `Get-D365AzureStorageFile`. Seems to be a holdover from https://github.com/d365collaborative/d365fo.tools/commit/5182b26ba0ce792751bfc70e4bc693c6ca0e3034 when the file information retrieval was refactored to use `Get-AzStorageBlob`.
Also does some code refactoring for better readability and maintainability, incorporating some suggestions by @FriedrichWeinmann in #870

:bug: Fix Get-D365AzureStorageFile

---

d365fo.tools/functions/invoke-d365sdpinstallude.ps1

Add logic to delete existing module folders before extracting new ones in `invoke-d365sdpinstallude.ps1`.
* Delete existing module folder if it exists before unzipping the new module.
* Add verbose message to indicate deletion of existing module folder.
* Adjust indentation and add missing newline at the end of the file.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/FH-Inway/d365fo.tools/pull/130?shareId=72e64ec3-0494-46b1-beed-248f3f79e2af).

Fix Invoke-D365SDPInstallUDE to handle updates and require admin privileges
