functions/invoke-d365scdpbundleinstall.ps1, functions/remove-d365database.ps1
* Minor change to the hotfixbundle install. Counting packages from the manifest itself, and more accurate monitoring of progress.
=> Improve quality of hotfixbundle progress

README.md, functions/import-d365aaduser.ps1, internal/sql/clear-azurebacpacdatabase.sql
Please check if our developpement standard was respected
Charles
=> Fix #64 issue

internal/sql/clear-azurebacpacdatabase.sql
Drop certificates that are tied to database users, which will cause errors when exporting the database if not dropped because then the corresponding user(s) can't be dropped later in the script.  These certs are created from User options > Account > Electronic signature > "Get certificate" button in D365FO UI
=> Drop certs that are tied to db users

d365fo.tools/internal/sql/clear-azurebacpacdatabase.sql
Aligning the preparation script for bacpac with the one on MS Docs:
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server
=> Align some SQL Scripts with the MS docs

.gitignore, README.md, d365fo.tools/d365fo.tools.psd1, d365fo.tools/functions/initialize-d365testautomationcertificate.ps1, d365fo.tools/functions/invoke-d365seleniumdownload.ps1, d365fo.tools/internal/functions/new-d365selfsignedcertificate.ps1
Added function to download and install selenium files for Regression Suite Automation Tool or PerfSDK.
2 other commits adjust the certificates function to properly reflect not using the makecert.exe anymore so removed parameters and XML documentation
=> Added function to download and install selenium files

d365fo.tools/d365fo.tools.psd1, d365fo.tools/d365fo.tools.psm1, d365fo.tools/docs/Add-D365AzureStorageConfig.md, d365fo.tools/docs/Invoke-D365AzureStorageDownload.md, d365fo.tools/docs/Invoke-D365AzureStorageUpload.md, d365fo.tools/functions/add-d365azurestorageconfig.ps1, d365fo.tools/functions/invoke-d365azurestoragedownload.ps1, d365fo.tools/functions/invoke-d365azurestorageupload.ps1, d365fo.tools/functions/set-d365activeazurestorageconfig.ps1, d365fo.tools/internal/scripts/variables.ps1, d365fo.tools/tests/functions/Add-D365AzureStorageConfig.Tests.ps1, d365fo.tools/tests/functions/Invoke-D365AzureStorageDownload.Tests.ps1, d365fo.tools/tests/functions/Invoke-D365AzureStorageUpload.Tests.ps1, d365fo.tools/tests/general/Help.Example.Tests.ps1
=> Merge 0.4.87

d365fo.tools/functions/clear-d365monitordata.ps1, d365fo.tools/internal/functions/add-wifconfigauthoritythumbprint.ps1, d365fo.tools/internal/functions/get-applicationenvironment.ps1, d365fo.tools/internal/scripts/variables.ps1
I'm a bit pushy, so we have a message prompted to the user every time the module loads and it has to default.
I want things to work as expected and I believe that the ServiceDrive is somewhat important based on how some of the MS tools rely on it.
=> Draft to fix #153

d365fo.tools/d365fo.tools.psd1, d365fo.tools/d365fo.tools.psm1, d365fo.tools/functions/clear-d365monitordata.ps1, d365fo.tools/internal/functions/add-wifconfigauthoritythumbprint.ps1, d365fo.tools/internal/functions/get-applicationenvironment.ps1, d365fo.tools/internal/scripts/variables.ps1
=> Merge 0.4.88 release

build/vsts-validate.ps1, d365fo.tools/functions/get-d365instancename.ps1, d365fo.tools/internal/functions/invoke-sqlpackage.ps1
- Fix Invoke SqlPackage allowing for filenames with spaces.
- Fix broken method reference in Get-D365InstanceName
=> Minor improvements

d365fo.tools/d365fo.tools.psd1, d365fo.tools/functions/invoke-d365bestpractice.ps1, d365fo.tools/functions/invoke-d365bestpractices.ps1
Added function to invoke best practices.
=> Added function to invoke best practices

d365fo.tools/functions/add-d365broadcastmessageconfig.ps1, d365fo.tools/functions/send-d365broadcastmessage.ps1, d365fo.tools/functions/set-d365activebroadcastmessageconfig.ps1
Allow to use Send-D365BroadcastMessage with OnPremise Environnement
Refactor code to use new PSAuthHelper function to get Bearer Token
#264
=> Send-D365BroadcastMessage with OnPremise

d365fo.tools/functions/invoke-d365dbsyncpartial.ps1, d365fo.tools/tests/functions/Invoke-D365DBSyncPartial.Tests.ps1, docs/Invoke-D365DBSyncPartial.md
- Added parameter for extension elements to sync
- Added parameter for model to sync
- Add assemblies to Invoke-D365DBSyncPartial
- Add begin/process sections to Invoke-D365DBSyncPartial
- Add code to process sync-able AOT elements from provided ModelName
- Added documentation + examples
=> [Invoke-D365DBSyncPartial] Added extension element sync + model sync

d365fo.tools/d365fo.tools.psd1, d365fo.tools/functions/invoke-d365dbsyncmodule.ps1, d365fo.tools/functions/invoke-d365dbsyncpartial.ps1, d365fo.tools/functions/invoke-d365modulefullcompilesync.ps1, d365fo.tools/internal/functions/get-d365syncelements.ps1, d365fo.tools/tests/functions/Invoke-D365DBSyncPartial.Tests.ps1, d365fo.tools/tests/functions/Invoke-D365ModuleFullCompileSync.Tests.ps1, docs/Invoke-D365ModuleFullCompileSync.md
New command made to compile and sync module(s). 
Compile and sync is done using the Invoke-D365ModuleFullCompile and Invoke-D365DBSyncPartial functions.
=> [Invoke-D365ModuleFullCompileSync] New command: compile and sync by module (match)

d365fo.tools/d365fo.tools.psd1, d365fo.tools/functions/disable-d365flight.ps1, d365fo.tools/functions/enable-d365flight.ps1, d365fo.tools/internal/sql/disable-flight.sql, d365fo.tools/internal/sql/enable-flight.sql
Two new Cmdlets to make the database entries to enable or disable a flight. The FlightingServiceCatalogID is expected to already be setup in the web.config
=> Add new Cmdlets to enable and disable flights

d365fo.tools/d365fo.tools.psd1, d365fo.tools/functions/invoke-d365sqlscript.ps1, d365fo.tools/tests/functions/Invoke-D365SqlScript.Tests.ps1, d365fo.tools/tests/general/Help.Example.Tests.ps1
Implemented Invoke-D365SqlCmd (#397 ) as an alias for Invoke-D365SqlScript and added a new parameter to Invoke-D365SqlScript for Command
=> Implement Invoke-D365SqlCmd

d365fo.tools/functions/new-d365bacpac.ps1
=> Remove Storage=File property from New-D365BacPac SQLPackage call

d365fo.tools/d365fo.tools.psd1, d365fo.tools/functions/import-d365aadapplication.ps1, d365fo.tools/internal/functions/import-aadapplicationIntod365fo.ps1, d365fo.tools/internal/functions/new-d365foaadapplication.ps1, d365fo.tools/internal/sql/add-aadapplicationintod365fo.sql
=> added Import-D365AadApplication

d365fo.tools/functions/get-d365defaultmodelfornewprojects.ps1, d365fo.tools/functions/set-d365defaultmodelfornewprojects.ps1
With the introduction of Visual Studio 2017, the location changed of
the DynamicsDevConfig.xml file. This new location was added.
=> D365DefaultModelForNewProjects: Add new location

d365fo.tools/functions/get-d365lcsapitoken.ps1, d365fo.tools/functions/get-d365lcsassetfile.ps1, d365fo.tools/functions/get-d365lcsassetvalidationstatus.ps1, d365fo.tools/functions/get-d365lcsdatabasebackups.ps1, d365fo.tools/functions/get-d365lcsdatabaseoperationstatus.ps1, d365fo.tools/functions/get-d365lcsdeploymentstatus.ps1, d365fo.tools/functions/invoke-d365lcsdatabaseexport.ps1, d365fo.tools/functions/invoke-d365lcsdatabaserefresh.ps1, d365fo.tools/functions/invoke-d365lcsdeployment.ps1, d365fo.tools/functions/invoke-d365lcsenvironmentstart.ps1, d365fo.tools/functions/invoke-d365lcsenvironmentstop.ps1, d365fo.tools/functions/invoke-d365lcsupload.ps1, d365fo.tools/functions/set-d365lcsapiconfig.ps1, d365fo.tools/internal/functions/complete-lcsupload.ps1, d365fo.tools/internal/functions/get-lcsassetfile.ps1, d365fo.tools/internal/functions/get-lcsassetvalidationstatus.ps1, d365fo.tools/internal/functions/get-lcsdatabasebackups.ps1, d365fo.tools/internal/functions/get-lcsdatabaseoperationstatus.ps1, d365fo.tools/internal/functions/get-lcsdeploymentstatus.ps1, d365fo.tools/internal/functions/start-lcsdatabaseexport.ps1, d365fo.tools/internal/functions/start-lcsdatabaserefresh.ps1, d365fo.tools/internal/functions/start-lcsdeployment.ps1, d365fo.tools/internal/functions/start-lcsenvironmentstartstop.ps1, d365fo.tools/internal/functions/start-lcsupload.ps1, d365fo.tools/internal/tepp/lcs.tepp.ps1
This PR is adding new LCS API endpoint urls to the script headers/docs. Please let me know if you want to see this done a different way.
Regards,
Billy
=> Add new LCS endpoint info

docs/Clear-D365TempDbTables.md
Update Example 1: Change invoke-D365CleanupTempDBTables to Clear-D365TempDbTables
=> Updated Example1 cmdlt to call

d365fo.tools/functions/install-d365supportingsoftware.ps1, d365fo.tools/tests/functions/Install-D365SupportingSoftware.ps1
This PR creates a command which will install or update Chocolatey and install the requested software package.  Once this is accepted we can make a Wiki article.
=> Initial commit of install-d365supportingsoftware command

d365fo.tools/functions/backup-d365devconfig.ps1, d365fo.tools/functions/backup-d365webconfig.ps1, d365fo.tools/functions/restore-d365devconfig.ps1, d365fo.tools/functions/set-d365defaultmodelfornewprojects.ps1, d365fo.tools/internal/scripts/variables.ps1
Added 2 new cmdlets to backup and restore the `DynamicsDevConfig.xml`.
=> ✨ Added cmdlets to backup and restore dev config

d365fo.tools/functions/start-d365environmentv2.ps1
Added support for exceptions throwing when services don't start
Removed computername param
=> Added Start-D365EnvironmentV2 #606

d365fo.tools/functions/start-d365environmentv2.ps1
Fixed the error as per @Splaxi suggestion, and this fixes also the formatting at the end output of the services.
=> Fixed index outside bounds + services format #623

d365fo.tools/functions/add-d365windowsdefenderrules.ps1
Adding some new windows defender exclusion based on the feedback from Brian Tubb on Yammer (https://www.yammer.com/dynamicsaxfeedbackprograms/#/Threads/show?threadId=1632959244066816) and also based on my current development setup.
=> feat: adding some more windows defender exclusion

d365fo.tools/functions/invoke-d365sdpinstall.ps1
=> :children_crossing: improve handling of relative paths

d365fo.tools/d365fo.tools.psd1, d365fo.tools/functions/disable-d365exception.ps1, d365fo.tools/functions/enable-d365exception.ps1, docs/Disable-D365Exception.md, wiki/Exception-handling.md, wiki/_Sidebar.md
- add Disable-D365Exception cmdlet
- improve exception handling documentation
Adresses the feedback from https://github.com/d365collaborative/d365fo.tools/issues/653.
=> improve exception handling

d365fo.tools/d365fo.tools.psd1, d365fo.tools/d365fo.tools.psm1
Update version information so that it matches version information on PowerShell Gallery.
=> Version: 0.6.73

README.md
PowerShell syntax highlighting added to code snippets in README.md.
=> Syntax highlighting added to README.

d365fo.tools/internal/sql/switch-database-tier1.sql
Fix for the issue described in the Yammer topic
https://www.yammer.com/dynamicsaxfeedbackprograms/threads/1994317149044736
=> Fix "Database is already open" issue

d365fo.tools/functions/add-d365windowsdefenderrules.ps1
We need to base64 encode sensitive paths, that triggers the windows defender
=> Fix: Defender was triggered

d365fo.tools/internal/sql/rename-computer.sql
This should be the easiest fix for issue #704
=> Add try/catch for sp_dropserver in sql script of Rename-D365ComputerName

d365fo.tools/d365fo.tools.psd1, d365fo.tools/functions/remove-d365lcsassetfile.ps1, d365fo.tools/internal/functions/remove-lcsassetfile.ps1, d365fo.tools/tests/functions/Remove-D365LcsAssetFile.Tests.ps1, docs/Remove-D365LcsAssetFile.md
Adds a new cmdlet to remove the asset from the LCS Asset Library.
=> ✨ Add new cmdlet Remove-D365LcsAssetFile

d365fo.tools/d365fo.tools.psd1, d365fo.tools/functions/add-d365moduletoremove.ps1, d365fo.tools/functions/new-d365isvlicense.ps1, d365fo.tools/functions/new-d365moduletoremove.ps1, d365fo.tools/internal/functions/add-filetopackage.ps1, d365fo.tools/tests/functions/Add-D365ModuleToRemove.Tests.ps1, d365fo.tools/tests/functions/New-D365ModuleToRemove.Tests.ps1, docs/Add-D365ModuleToRemove.md, docs/New-D365ISVLicense.md, docs/New-D365ModuleToRemove.md
=> :sparkles: New cmdlet(s) for ModuleToRemove.txt to uninstall a package #710

d365fo.tools/functions/get-d365lcsapitoken.ps1
See https://github.com/d365collaborative/d365fo.tools/issues/736
=> :bug: fix the name of the LCS API URI config value

.github/workflows/update-generated-text.yml, build/buildtools.ps1, build/format-commentbasedhelp.ps1, build/generate-parameterunittests.ps1, build/update-docs.ps1
=> 👷 Add a GitHub action that executes the scripts of the building tools

d365fo.tools/functions/import-d365bacpac.ps1, d365fo.tools/internal/sql/set-bacpacvaluessql.sql
=> 🚀 . Incorrect syntax if dbname include hypern

d365fo.tools/functions/get-d365module.ps1
=> add fallback for failing ListModulesInDependencyOrder

d365fo.tools/functions/invoke-d365dbsync.ps1
=> Invalid SQL connection string fix

d365fo.tools/functions/invoke-d365installsqlpackage.ps1
=> update url of MS documentation page about sqlpackage downloads

d365fo.tools/functions/set-d365rsatconfiguration.ps1
=> add parameter for RSAT config file

d365fo.tools/internal/scripts/variables.ps1
=> :bug: include non-us/non-global region environments

d365fo.tools/d365fo.tools.psd1, d365fo.tools/functions/new-d365entraintegration.ps1, d365fo.tools/internal/functions/set-browserbookmark.ps1, d365fo.tools/tests/functions/New-D365EntraIntegration.Tests.ps1, docs/New-D365EntraIntegration.md
=> adds new cmdlet New-D365EntraIntegration (#789)

d365fo.tools/bin/d365fo.tools-index.json, d365fo.tools/d365fo.tools.psd1, d365fo.tools/functions/get-d365lcsenvironmentrsatcertificate.ps1, d365fo.tools/internal/functions/get-lcsenvironmentrsatcertificate.ps1, d365fo.tools/tests/functions/Get-D365LcsEnvironmentRsatCertificate.Tests.ps1, docs/Get-D365LcsEnvironmentRsatCertificate.md
=> Feature: Get-D365LcsEnvironmentRsatCertificate

wiki/Tutorial-List-Commands.md
URL was correct, but inline text was duplicated.
(I forgot to branch it first, is super-simple change, let me know if a branch is 100% required)
=> Wiki entry Fix wrong link text 

d365fo.tools/functions/import-d365aaduser.ps1
=> Selecting Id as ObjectId #885 
